#+title: Data Curation Tool

* Run Sequence
Entry Point: ```interface.component.ts```
- The interface component uses the ```getBaseUrl()``` to get the baseURL
- The interface component uses the ```getParameterByName(name)``` to get the siteURL, _id, metaId, and dvLocale
- The dvLocale is used to set the language
- If there is not siteURL or _id, the uri created uses a file in the assets folder
- if there is a siteURL, there are more checks to create the uri
- The Uri created is passed on ```getDDI()```

* Potential Problems
- Converting the XML to JSON on the client
* State management
The app is an entire state management for a dataset.
** TODO Users should be able to change variable information. (excluding variable ID and name)
** TODO Users should be able to create groups

** ACTIONS
*** Dataset Load Pending
API has been called and request is in progress.
*** Dataset Load Success
API has responded with data
*** Dataset Load Error
API could not complete request
*** Dataset Download
Download XML to local machine.
*** Dataset Local Save
Save dataset changes into local storage
*** Dataset Upload Pending
API to upload changed dataset called and in progress.
*** Dataset Upload Success
API to upload changed dataset completed successfully.
*** Dataset Upload Error
API to upload changed dataset could not complete.
*** Variable Change Detail
Change Variable metadata
*** Variable Add to SelectedGroup
*** Group Create New
*** Group Remove
*** Group Change Name
*** Group Add SelectedGroup
