#+title: Data Curation Tool

* Run Sequence
Entry Point: ```interface.component.ts```
- The interface component uses the ```getBaseUrl()``` to get the baseURL
- The interface component uses the ```getParameterByName(name)``` to get the siteURL, _id, metaId, and dvLocale
- The dvLocale is used to set the language
- If there is not siteURL or _id, the uri created uses a file in the assets folder
- if there is a siteURL, there are more checks to create the uri
- The Uri created is passed on ```getDDI()```

* Potential Problems
- Converting the XML to JSON on the client
* State management
The app is an entire state management for a dataset.
** TODO Users should be able to change variable information. (excluding variable ID and name)
** TODO Users should be able to create groups

** ACTIONS
*API CALLS*
*** Fetch Dataset
Fetch the dataset for the page using the given fileId and siteUrl
*** Dataset Load Pending
API has been called and request is in progress.
*** Dataset Load Success
API has responded with data
*** Dataset Load Error
API could not complete request
*** Dataset Upload Request
Call Dataverse API to upload local changes.
*** Dataset Upload Pending
API to upload changed dataset called and in progress.
*** Dataset Upload Success
API to upload changed dataset completed successfully.
*** Dataset Upload Error
API to upload changed dataset could not complete.
*LOCAL CHANGES*
*** Dataset Download
Download XML to local machine.
*** Dataset Local Save
Save dataset changes into local storage
*** Variable Change Detail
Change Variable metadata
*** Variable Add to SelectedGroup
Add new variable to list of currently selected variables for bulk edit.
*** Group Create New
Create new empty variable group.
*** Group Remove
Remove a specified variable group.
*** Group Change Name
Change a specified variable group name.
*** Group Add SelectedGroup
Add the list of currently selected variables to a specified variable group.

** REDUCERS
*** Fetch Dataset
Change dataset status to pending.
*** Dataset Success
Change dataset status to success and load dataset into state.
*** Dataset Load Error
Change dataset status to error.
*** Dataset Upload Request
Change upload status to pending.
*** Dataset Success
Change uploaded status to success.
*** Dataset Load Error
Change uploaded status to error.
*** Variable Change Detail
Return new object for specified variable, and change uploaded status to null.
*** Variable Add to SelectedGroup
Add variable to list of selected variables.
*** Group Create New
Add new empty variable group to state, and change uploaded status to null.
*** Group Remove
Remove a specified variable group from state, and change uploaded status to null.
*** Group Change Name
Change a specified variable's 'name' property, and change uploaded status to null.
*** Group Add SelectedGroup
Add the list of currently selected variables to a specified variable group.
